spring:
    application:
        name: api
    profiles:
        active: dev

springdoc:
    swagger-ui:
        path: /swagger-ui.html  # prod false
    api-docs:
        path: /api-docs         # prod false
