name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Generate JOOQ classes
        run: ./gradlew jooqCodegen

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/lightsail_key
          chmod 600 ~/.ssh/lightsail_key

      - name: Deploy to Lightsail
        env:
          PROD_YAML_BASE64: ${{ secrets.PROD_YAML_BASE64 }}
        run: |
          # JAR 파일 검증
          JAR_FILE=build/libs/api-0.0.1-SNAPSHOT.jar
          if [ ! -f "$JAR_FILE" ]; then
            echo "Error: JAR file $JAR_FILE not found"
            exit 1
          fi
          
          # PROD_YAML_BASE64 값의 길이 확인 (빈 값 여부 점검)
          echo "PROD_YAML_BASE64 length: ${#PROD_YAML_BASE64}"
          if [ -z "$PROD_YAML_BASE64" ]; then
            echo "Error: PROD_YAML_BASE64 is empty"
            exit 1
          fi
          
          # Base64 디코딩해서 YAML 파일 생성
          echo "$PROD_YAML_BASE64" | tr -d '\n' | base64 -d > application-prod.yaml || echo "Base64 decoding failed"
          
          # 생성된 YAML 파일의 크기 확인 (빈 값 여부 점검)
          YAML_SIZE=$(wc -c < application-prod.yaml)
          echo "application-prod.yaml size: $YAML_SIZE bytes"
          if [ "$YAML_SIZE" -eq 0 ]; then
            echo "Error: application-prod.yaml is empty"
            exit 1
          fi
          
          # YAML 파일 전송
          scp -i ~/.ssh/lightsail_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no application-prod.yaml ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/home/${{ secrets.SSH_USER }}/application-prod.yaml
          # JAR 파일 전송
          scp -i ~/.ssh/lightsail_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no "$JAR_FILE" ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/home/${{ secrets.SSH_USER }}/api-0.0.1-SNAPSHOT.jar
          # 배포 스크립트 전송
          scp -i ~/.ssh/lightsail_key -P ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no deploy.sh ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/home/${{ secrets.SSH_USER }}/deploy.sh
          # 스크립트 실행
          ssh -i ~/.ssh/lightsail_key -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST }} \
            "chmod +x /home/${{ secrets.SSH_USER }}/deploy.sh && /home/${{ secrets.SSH_USER }}/deploy.sh ${{ secrets.LOGSTASH_HOST }} ${{ secrets.LOGSTASH_PORT }}"
