name: Java CI with Gradle

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Generate JOOQ classes
        run: ./gradlew jooqCodegen

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      # JAR 파일 아티팩트(임시저장)로 저장 (CD에서 사용)
      - name: Upload JAR for CD
        uses: actions/upload-artifact@v4
        with:
          name: application
          path: build/libs/*.jar